### ISSUE TITLE
有个小bug

### ISSUE THREAD

**Issue by rikkely** [beiklive/PopupClock#12]
就是我睡眠了一晚上电脑 第二天打开 这个时钟就没有继续出来了 只能重新启动才会正常出来

**Comment by beiklive** [comment]
收到

**Comment by beiklive** [comment]
你的设置发我看一下

**Comment by rikkely** [comment]
![image](https://user-images.githubusercontent.com/111125324/220804135-9b984ac5-67bf-4097-84e2-20afad69ce2c.png)

**Comment by beiklive** [comment]
坏了，看不出哪里有问题

**Comment by ohto-ai** [comment]
@beiklive 你需要把运行状态和用户操作记录到日志里，考虑下加进去吧

**Comment by beiklive** [comment]
可能是定时器超时吧

**Comment by beiklive** [comment]
> @beiklive 你需要把运行状态和用户操作记录到日志里，考虑下加进去吧
让我考虑两下

**Comment by rikkely** [comment]
还发现了一个问题，我今天睡眠之后 没有退出 直接点设置 弹出来的这个时钟变很丑的长方形被拉长了，是因为我有用HDMI扩展屏幕的原因吗

**Comment by beiklive** [comment]
> 还发现了一个问题，我今天睡眠之后 没有退出 直接点设置 弹出来的这个时钟变很丑的长方形被拉长了，是因为我有用HDMI扩展屏幕的原因吗

开一个新的issue描述吧， 最好有截图

**Comment by beiklive** [comment]
> 可能是定时器超时吧

![image](https://user-images.githubusercontent.com/73771431/220806836-64a72a08-c1b4-44d2-90e6-4474b704ee91.png)

**Comment by rikkely** [comment]
明天看看 因为一闪就过去了

**Comment by rikkely** [comment]
![1677124995226](https://user-images.githubusercontent.com/111125324/220819027-051bdf4d-3186-4c01-af60-0fe3ddd5ff09.jpg)
![1677124995236](https://user-images.githubusercontent.com/111125324/220819040-f2306c1d-ef12-4252-b51d-9ac80ae4ee01.jpg)

**Comment by rikkely** [comment]
明明只悬停60s 到时间了没有缩进去

**Comment by rikkely** [comment]
不知道怎么回事

**Comment by beiklive** [comment]
@rikkely  使用新的realse， 我增加了日志的功能，你报的bug我还没解

**Comment by rikkely** [comment]
那我下载你的realse 再试试

**Comment by beiklive** [comment]
> 那我下载你的realse 再试试

release 用 v3.0.0 的

**Comment by beiklive** [comment]
> 那我下载你的realse 再试试
还没上传好呢

**Comment by rikkely** [comment]
我看看 我刚刚下载了个2.几的

**Comment by rikkely** [comment]
看到源码传了 我自己编译吗 还是你还没传好

**Comment by beiklive** [comment]
> 看到源码传了 我自己编译吗 还是你还没传好

上传好了

**Comment by rikkely** [comment]
![1677144720239](https://user-images.githubusercontent.com/111125324/220871149-65d290dd-bfea-4cd2-be31-fb49ea869994.jpg)

**Comment by rikkely** [comment]
bug更多了 初始化白屏 右键设置的时候文字乱码 然后就是会变很丑的长方形 还有整个时钟变小了

**Comment by rikkely** [comment]
我继续用吗 还是优化下

**Comment by beiklive** [comment]
> 就是我睡眠了一晚上电脑 第二天打开 这个时钟就没有继续出来了 只能重新启动才会正常出来

这个问题目前还没测试出来，可以用最新版本看看。

**Comment by rikkely** [comment]
好的 辛苦啦

**Comment by beiklive** [comment]
先关掉了，有问题再reopen
