### ISSUE TITLE
悬停后未触发缩回

### ISSUE THREAD

**Issue by beiklive** [beiklive/PopupClock#13]
![1677124995226](https://user-images.githubusercontent.com/111125324/220819027-051bdf4d-3186-4c01-af60-0fe3ddd5ff09.jpg)

![1677124995236](https://user-images.githubusercontent.com/111125324/220819040-f2306c1d-ef12-4252-b51d-9ac80ae4ee01.jpg)

_Originally posted by @rikkely in https://github.com/beiklive/PopupClock/issues/12#issuecomment-1441191819_

**Comment by beiklive** [comment]
状态切换功能已优化，请使用最新版本测试。💖💖💖

**Comment by rikkely** [comment]
![image](https://user-images.githubusercontent.com/111125324/221734962-b6b090b3-14b4-4040-babd-74f302055ccb.png)

**Comment by rikkely** [comment]
![image](https://user-images.githubusercontent.com/111125324/221735001-227bc09b-bdbf-44a6-9fa2-58bb5ec9b617.png)
已经设置好了 不缩回去

**Comment by rikkely** [comment]
还有个就是特别小  
![image](https://user-images.githubusercontent.com/111125324/221735180-a33a18e9-4107-4979-98e6-0a014dc178db.png)

**Comment by beiklive** [comment]
小是分辨率导致的

**Comment by beiklive** [comment]
设置完效果之后点ok保存设置，会在下一次弹出的时间触发

**Comment by rikkely** [comment]
我前面那个截图点完ok了 但是一直时钟一直悬浮着没有隐藏回去

**Comment by beiklive** [comment]
停留时间需要设置在 < 30s, 最多29秒，

**Comment by beiklive** [comment]
我看一下为什么会这样

**Comment by rikkely** [comment]
好

**Comment by beiklive** [comment]
已修复， 请使用v4.3-release版本

**Comment by rikkely** [comment]
好嘞

**Comment by beiklive** [comment]
修了点bug, 用v4.4-release版本吧

**Comment by rikkely** [comment]
那个分辨率大小能调吗 我最开始那个版本大小挺好的 这些版本都变小了好多

**Comment by beiklive** [comment]
> 那个分辨率大小能调吗 我最开始那个版本大小挺好的 这些版本都变小了好多

下个版本添加大小调整的功能
