### ISSUE TITLE
睡眠之后时钟变很丑的长方形

### ISSUE THREAD

**Issue by beiklive** [beiklive/PopupClock#14]
还发现了一个问题，我今天睡眠之后 没有退出 直接点设置 弹出来的这个时钟变很丑的长方形被拉长了，是因为我有用HDMI扩展屏幕的原因吗

_Originally posted by @rikkely in https://github.com/beiklive/PopupClock/issues/12#issuecomment-1441132909_

**Comment by rikkely** [comment]
![image](https://user-images.githubusercontent.com/111125324/220826327-75faa8c0-7edb-4a99-9915-0d7bd5b5a4f6.png)

**Comment by rikkely** [comment]
![image](https://user-images.githubusercontent.com/111125324/220826374-49555234-cd90-4444-972a-d22cfc5873e8.png)

**Comment by rikkely** [comment]
就是这样

**Comment by beiklive** [comment]
绘图部分已修改，请使用最新版本测试。💖💖💖
