### ISSUE TITLE
v2.1.9版本部分绘图闪烁

### ISSUE THREAD

**Issue by chadspring** [beiklive/PopupClock#15]
**Bug描述**
部分绘图闪烁
任务栏右键菜单乱码

**复现步骤**

**预期行为**

**截图录屏**
绘图闪烁gif截图如下
![无标题视频——使用Clipchamp制作](https://user-images.githubusercontent.com/15319340/220861156-7c62041e-55b5-485a-b4c6-6eaeabe88382.gif)
乱码截图如下
![1677142538865](https://user-images.githubusercontent.com/15319340/220861384-a9b6be23-caab-41e2-b02f-0883a74433ed.jpg)

**运行环境 (请填写以下信息):**
 - 系统: Windows 11 专业版 22H2
 - 软件版本：v2.1.9
 - 显示器：2560 x 1440 60HZ

**附件信息**

**Comment by chadspring** [comment]
感谢大佬

**Comment by chadspring** [comment]
补充：系统设置-屏幕-缩放和布局-缩放为125%，不知道会不会有影响

**Comment by beiklive** [comment]
收到

**Comment by beiklive** [comment]
代码已修改，请使用最新版本测试。💖💖💖
