### ISSUE TITLE
 怎么用action编译qt啊

### ISSUE THREAD

**Issue by beiklive** [beiklive/PopupClock#4]
@Ohto-Ai   怎么用action编译qt啊

**Comment by ohto-ai** [comment]
看我ppin仓库

**Comment by ohto-ai** [comment]
https://github.com/Ohto-Ai/ppin/blob/master/.github/workflows/windows.yml#L86

判断提交了tag并且是v开头，就发布一个release

**Comment by beiklive** [comment]
突然想起来我收藏过模板

**Comment by beiklive** [comment]
![image](https://user-images.githubusercontent.com/73771431/202337293-5e479795-e65d-41ca-a6cf-9454e65b4220.png)
这种passing要怎么搞呀

**Comment by ohto-ai** [comment]
点进action的workflow，然后create status badge

**Comment by beiklive** [comment]
真是奇葩，本地编译的时候会有一个ui文件报找不到头文件

**Comment by beiklive** [comment]
> https://github.com/Ohto-Ai/ppin/blob/master/.github/workflows/windows.yml#L86
> 
> 判断提交了tag并且是v开头，就发布一个release

就是每次提交的时候要添加tag是吧

**Comment by ohto-ai** [comment]
不是，你要发布的时候，给某个commit添加一个tag，然后把tag push上去

**Comment by beiklive** [comment]
> 不是，你要发布的时候，给某个commit添加一个tag，然后把tag push上去

```
git commit XXXXXXXXXXX
git tag v1.0.0
git push --tags
```

like this?

**Comment by ohto-ai** [comment]
对，你要记得tag是可以给过去的提交打tag的，不加id就是最近的一次

**Comment by beiklive** [comment]
> 对，你要记得tag是可以给过去的提交打tag的，不加id就是最近的一次

ok
