### ISSUE TITLE
背景出现跟随秒针一闪一闪的透明块

### ISSUE THREAD

**Issue by chadspring** [beiklive/PopupClock#6]
![Snipaste_2023-02-16_15-27-31](https://user-images.githubusercontent.com/15319340/219296786-0c741366-5b96-4a63-be15-32948d5c0ad9.png)
很大概率会出现

**Comment by beiklive** [comment]
重启一下，然后你记录一下复现这个问题的过程，发在这里。

**Comment by beiklive** [comment]
你的用的是高刷屏？

**Comment by beiklive** [comment]
已修复

**Comment by ohto-ai** [comment]
Fixed by 97dd45fb357421a1479c13d44f443502eeac3a4b

**Comment by chadspring** [comment]
不好意思，最近没上，没有及时回复消息，抱歉
新版好像仍然有bug，如下图，我将新开一个lessues
![无标题视频——使用Clipchamp制作](https://user-images.githubusercontent.com/15319340/220860401-c8069195-cc1e-42ab-a93d-122e1980e3b9.gif)
