### ISSUE TITLE
[Enhancement] 考虑下优化绘制的效率

### ISSUE THREAD

**Issue by ohto-ai** [beiklive/PopupClock#7]
https://github.com/beiklive/PopupClock/blob/master/src/DrawClock.cpp#L51

1. 绘制指针不应该多次获取时间，应该将时间作为参数传入；
2. 可以考虑双缓冲，一般来说Qt5能自动处理闪烁问题，但是可以尝试能否通过双缓冲来修复偶发的闪烁现象；
3. 多次在`QPainter::save`之前设置画笔和画刷，反而失去了`save`/`restore`的作用；
4. 将一些MagicNumber装进类内的`constexpr`成员，如220、110。

**Comment by beiklive** [comment]
当年不知道哪里抄的陈年老代码

**Comment by ohto-ai** [comment]
来做下优化

**Comment by beiklive** [comment]
> 来做下优化

等我在mac上装好QT

**Comment by ohto-ai** [comment]
great

**Comment by beiklive** [comment]
<img width="950" alt="image" src="https://user-images.githubusercontent.com/73771431/219599785-17294d1e-b9f4-43f2-b82a-208574e9e535.png">
速度感人

**Comment by ohto-ai** [comment]
:rofl:

**Comment by ohto-ai** [comment]
:rofl: 🤣 ![](https://github.githubassets.com/images/icons/emoji/unicode/1f923.png)

![image](https://user-images.githubusercontent.com/46275725/219600760-f6e34f70-574d-4ecb-813d-56d8078be098.png)
![image](https://user-images.githubusercontent.com/46275725/219600810-6d38034f-49e6-4ca3-b29c-fe8f82d5fc1b.png)

**Comment by beiklive** [comment]
duang
