### ISSUE TITLE
好像少了文件启动不了

### ISSUE THREAD

**Issue by rikkely** [beiklive/PopupClock#9]
少了个ui_PopupClock.h头文件

**Comment by beiklive** [comment]
应该不差文件



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年2月17日(周五) 下午3:32
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [beiklive/PopupClock] 好像少了文件启动不了 (Issue #9)




 
少了个ui_PopupClock.h头文件

**Comment by rikkely** [comment]
我找到了  但是启动的时候就是报找不到头文件  但是我点击这个报错 跳转到这个头文件了

**Comment by rikkely** [comment]
方便加个联系方式 我问问你吗

**Comment by rikkely** [comment]
我干java的  不太会用qt这个

**Comment by rikkely** [comment]
我看报错是 在build ui_PopupClock.h的时候找不到DrawClock.h这个文件

**Comment by beiklive** [comment]
直接去release下载就好了呀，那边有我打包的好的可执行文件。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年2月17日(周五) 下午3:39
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [beiklive/PopupClock] 好像少了文件启动不了 (Issue #9)




 
方便加个联系方式 我问问你吗

**Comment by rikkely** [comment]
我好像下载不了 说不安全...

**Comment by rikkely** [comment]
可以下载了  谢谢 最开始没看到  还去下了qt

**Comment by ohto-ai** [comment]
Great

**Comment by rikkely** [comment]
感谢大佬

**Comment by ohto-ai** [comment]
> 直接去release下载就好了呀，那边有我打包的好的可执行文件。
> […](#)
> ---原始邮件--- 发件人: ***@***.***&gt; 发送时间: 2023年2月17日(周五) 下午3:39 收件人: ***@***.***&gt;; 抄送: ***@***.******@***.***&gt;; 主题: Re: [beiklive/PopupClock] 好像少了文件启动不了 (Issue #9) 方便加个联系方式 我问问你吗 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***&gt;

#10

**Comment by beiklive** [comment]
编译问题已修复

**Comment by rikkely** [comment]
是不是那个头文件路径引错了，我加上./src/就可以编译了

**Comment by beiklive** [comment]
是的
